name: clang-format lint

on: 
  pull_request:
    branches: 
      - master

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.3.1
      with:
        source: '.'
        exclude: ''
        extensions: 'h,c'
